######################################################################
# Automatically generated by qmake (1.07a) Thu Jul 19 02:11:17 2007
######################################################################

TEMPLATE = app
CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += getimages.cpp
